# Generated by Django 6.0.6 on 2026-06-23 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scenarios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("websocket_channel", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="scenarios.scenario",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("articulation_score", models.FloatField(blank=True, null=True)),
                ("grammar_score", models.FloatField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("pace_score", models.FloatField(blank=True, null=True)),
                ("filler_word_score", models.FloatField(blank=True, null=True)),
                ("overall_score", models.FloatField(blank=True, null=True)),
                (
                    "filler_words_detail",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g. {"um": 4, "uh": 2, "like": 7}',
                    ),
                ),
                (
                    "grammar_issues",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {text, suggestion, severity} dicts",
                    ),
                ),
                (
                    "suggestions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of improvement suggestion strings",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="LLM-generated overall summary"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_report",
                        to="speakup_sessions.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "feedback report",
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "speaker",
                    models.CharField(
                        choices=[("user", "User"), ("ai", "AI")], max_length=10
                    ),
                ),
                ("content", models.TextField()),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="STT confidence score (0.0–1.0), null for AI turns",
                        null=True,
                    ),
                ),
                (
                    "audio_start_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Offset from session start in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "audio_duration_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("sequence_order", models.PositiveIntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="speakup_sessions.session",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_order", "timestamp"],
            },
        ),
    ]
